#!/usr/bin/env python3

import os
import sys

THIS = os.path.dirname(os.path.abspath(sys.argv[0]))

sys.path.append(os.path.join(THIS,'lib','src'))

if __name__ == '__main__':
    from tools.api.heroes3.trainer import main
    main()


