from ..arch import Slot
from ..artifact import Artifact
from ..spell import Spells


DATA = []

DATA.append(Artifact.Major("Ambassador's Sash", Slot.cloak))
DATA.append(Artifact.Treasure("Amulet of the Undertaker", Slot.neck))
DATA.append(Artifact.Major("Angel Feather Arrows", Slot.side))
DATA.append(Artifact.Relic("Angel Wings", Slot.cloak))
DATA.append(Artifact.Minor("Armor of Wonder", Slot.armor, [+1, +1, +1, +1]))
DATA.append(Artifact.Major("Arms of Legion", Slot.side))
DATA.append(Artifact.Treasure("Badge of Courage", Slot.side))
DATA.append(Artifact.Treasure("Bird of Perception", Slot.side))
DATA.append(Artifact.Minor("Blackshard of the Dead Knight", Slot.weapon, [+3,  0,  0,  0]))
DATA.append(Artifact.Relic("Boots of Levitation", Slot.feet))
DATA.append(Artifact.Relic("Boots of Polarity", Slot.feet))
DATA.append(Artifact.Minor("Boots of Speed", Slot.feet))
DATA.append(Artifact.Treasure("Bow of Elven Cherrywood", Slot.side))
DATA.append(Artifact.Minor("Bowstring of the Unicorns's Mane", Slot.side))
DATA.append(Artifact.Major("Breastplate of Brimstone", Slot.armor, [0,  0, +5,  0]))
DATA.append(Artifact.Treasure("Breastplate of Petrified Wood", Slot.armor, [0,  0, +1,  0]))
DATA.append(Artifact.Minor("Buckler of the Gnoll King", Slot.shield, [0, +4,  0,  0]))
DATA.append(Artifact.Treasure("Cape of Conjuring", Slot.cloak))
DATA.append(Artifact.Major("Cape of Velocity", Slot.cloak))
DATA.append(Artifact.Treasure("Cards of Prophecy", Slot.side))
DATA.append(Artifact.Relic("Celestial Necklace of Bliss", Slot.neck, [+3, +3, +3, +3]))
DATA.append(Artifact.Treasure("Centaur's Axe", Slot.weapon, [+2,  0,  0,  0]))
DATA.append(Artifact.Treasure("Charm of Mana", Slot.side))
DATA.append(Artifact.Treasure("Clover of Fortune", Slot.side))
DATA.append(Artifact.Treasure("Collar of Conjuring", Slot.neck))
DATA.append(Artifact.Treasure("Crest of Valor", Slot.side))
DATA.append(Artifact.Relic("Crown of Dragontooth", Slot.helm, [0,  0, +4, +4]))
DATA.append(Artifact.Minor("Crown of the Supreme Magi", Slot.helm, [0,  0,  0, +4]))
DATA.append(Artifact.Major("Dead Man's Boots", Slot.feet))
DATA.append(Artifact.Major("Diplomat's Ring", Slot.hand))
DATA.append(Artifact.Relic("Dragon Scale Armor", Slot.armor, [+4, +4,  0,  0]))
DATA.append(Artifact.Major("Dragon Scale Shield", Slot.shield, [0,  0, +3, +3]))
DATA.append(Artifact.Minor("Dragon Wing Tabard", Slot.cloak))
DATA.append(Artifact.Treasure("Dragonbone Greaves", Slot.feet, [0,  0, +1, +1]))
DATA.append(Artifact.Minor("Emblem of Cognizance", Slot.side))
DATA.append(Artifact.Major("Endless Bag of Gold", Slot.side))
DATA.append(Artifact.Major("Endless Purse of Gold", Slot.side))
DATA.append(Artifact.Relic("Endless Sack of Gold", Slot.side))
DATA.append(Artifact.Minor("Equestrian's Gloves", Slot.hand))
DATA.append(Artifact.Major("Everflowing Crystal Cloak", Slot.cloak))
DATA.append(Artifact.Major("Everpouring Vial of Mercury", Slot.side))
DATA.append(Artifact.Major("Eversmoking Ring of Sulfur", Slot.hand))
DATA.append(Artifact.Major("Garniture of Interference", Slot.neck))
DATA.append(Artifact.Treasure("Glyph of Gallantry", Slot.side))
DATA.append(Artifact.Major("Golden Bow", Slot.side))
DATA.append(Artifact.Minor("Greater Gnoll's Flail", Slot.weapon, [+4,  0,  0,  0]))
DATA.append(Artifact.Major("Head of Legion", Slot.side))
DATA.append(Artifact.Major("Hellstorm Helmet", Slot.helm, [0,  0,  0, +5]))
DATA.append(Artifact.Minor("Helm of Chaos", Slot.helm, [0,  0,  0, +3]))
DATA.append(Artifact.Relic("Helm of Heavenly Enlightenment", Slot.helm, [+6, +6, +6, +6]))
DATA.append(Artifact.Treasure("Helm of the Alabaster Unicorn", Slot.helm, [0,  0,  0, +1]))
DATA.append(Artifact.Treasure("Hourglass of the Evil Hour", Slot.side))
DATA.append(Artifact.Minor("Inexhaustable Cart of Lumber", Slot.side))
DATA.append(Artifact.Minor("Inexhaustable Cart of Ore", Slot.side))
DATA.append(Artifact.Treasure("Ladybird of Luck", Slot.side))
DATA.append(Artifact.Treasure("Legs of Legion", Slot.side))
DATA.append(Artifact.Relic("Lion's Shield of Courage", Slot.shield, [+4, +4, +4, +4]))
DATA.append(Artifact.Minor("Loins of Legion", Slot.side))
DATA.append(Artifact.Treasure("Mystic Orb of Mana", Slot.side))
DATA.append(Artifact.Major("Necklace of Dragonteeth", Slot.neck, [0,  0, +3, +3]))
DATA.append(Artifact.Major("Necklace of Ocean Guidance", Slot.neck))
DATA.append(Artifact.Treasure("Necklace of Swiftness", Slot.neck))
DATA.append(Artifact.Major("Ogre's Club of Havoc", Slot.weapon, [+5,  0,  0,  0]))
DATA.append(Artifact.Major("Orb of Driving Rain", Slot.side))
DATA.append(Artifact.Major("Orb of Firmament", Slot.side))
DATA.append(Artifact.Relic("Orb of Inhibition", Slot.side))
DATA.append(Artifact.Major("Orb of Silt", Slot.side))
DATA.append(Artifact.Major("Orb of Tempestous Fire", Slot.side))
DATA.append(Artifact.Relic("Orb of Vulnerability", Slot.side))
DATA.append(Artifact.Major("Pendant of Agitation", Slot.neck))
DATA.append(Artifact.Major("Pendant of Courage", Slot.neck))
DATA.append(Artifact.Treasure("Pendant of Death", Slot.neck))
DATA.append(Artifact.Treasure("Pendant of Dispassion", Slot.neck))
DATA.append(Artifact.Treasure("Pendant of Free Will", Slot.neck))
DATA.append(Artifact.Treasure("Pendant of Holiness", Slot.neck))
DATA.append(Artifact.Treasure("Pendant of Life", Slot.neck))
DATA.append(Artifact.Major("Pendant of Second Sight", Slot.neck))
DATA.append(Artifact.Treasure("Pendant of Total Recall", Slot.neck))
DATA.append(Artifact.Treasure("Quiet Eye of the Dragon", Slot.hand, [+1, +1,  0,  0]))
DATA.append(Artifact.Major("Recanter's Cloak", Slot.cloak))
DATA.append(Artifact.Minor("Red Dragon Flame Tongue", Slot.weapon, [+2, +2,  0,  0]))
DATA.append(Artifact.Minor("Rib Cage", Slot.armor, [0,  0, +2,  0]))
DATA.append(Artifact.Treasure("Ring of Conjuring", Slot.hand))
DATA.append(Artifact.Major("Ring of Infinite Gems", Slot.hand))
DATA.append(Artifact.Minor("Ring of Life", Slot.hand))
DATA.append(Artifact.Major("Ring of the Wayfarer", Slot.hand))
DATA.append(Artifact.Treasure("Ring of Vitality", Slot.hand))
DATA.append(Artifact.Relic("Sandals of the Saint", Slot.feet, [+2, +2, +2, +2]))
DATA.append(Artifact.Minor("Scales of the Greater Balilisk", Slot.armor, [0,  0, +3,  0]))
DATA.append(Artifact.Relic("Sea Captain's Hat", Slot.helm))
DATA.append(Artifact.Relic("Sentinel's Shield", Slot.shield, [-3, 12,  0,  0]))
DATA.append(Artifact.Major("Shackles of War", Slot.side))
DATA.append(Artifact.Major("Shield of the Damned", Slot.shield, [0, +6,  0,  0]))
DATA.append(Artifact.Treasure("Shield of the Dwarven Lords", Slot.shield, [0, +2,  0,  0]))
DATA.append(Artifact.Minor("Shield of the Yawning Dead", Slot.shield, [0, +3,  0,  0]))
DATA.append(Artifact.Treasure("Skull Helmet", Slot.helm, [0,  0,  0, +2]))
DATA.append(Artifact.Treasure("Speculum", Slot.side))
DATA.append(Artifact.Relic("Spellbinder's Hat", Slot.helm, None, [spell.name for spell in Spells('base').Level(5)]))
DATA.append(Artifact.Major("Sphere of Permanence", Slot.side))
DATA.append(Artifact.Treasure("Spirit of Oppression", Slot.side))
DATA.append(Artifact.Treasure("Spyglass", Slot.side))
DATA.append(Artifact.Major("Statesman's Medal", Slot.side))
DATA.append(Artifact.Treasure("Still Eye of the Dragon", Slot.hand))
DATA.append(Artifact.Treasure("Stoic Watchman", Slot.side))
DATA.append(Artifact.Major("Surcoat of Counterpoise", Slot.cloak))
DATA.append(Artifact.Major("Sword of Hellfire", Slot.weapon, [+6,  0,  0,  0]))
DATA.append(Artifact.Relic("Sword of Judgement", Slot.weapon, [+5, +5, +5, +5]))
DATA.append(Artifact.Treasure("Talisman of Mana", Slot.side))
DATA.append(Artifact.Major("Targ of the Rampaging Ogre", Slot.shield, [0, +5,  0,  0]))
DATA.append(Artifact.Relic("Thunder Helmet", Slot.helm, [0,  0, -2, 10]))
DATA.append(Artifact.Relic("Titan's Cuirass", Slot.armor, [0,  0, 10, -2]))
DATA.append(Artifact.Relic("Titan's Gladius", Slot.weapon, [12, -3,  0,  0]))
DATA.append(Artifact.Relic("Tome of Air", Slot.side, None, [spell.name for spell in Spells('base').Air()]))
DATA.append(Artifact.Relic("Tome of Earth", Slot.side, None, [spell.name for spell in Spells('base').Earth()]))
DATA.append(Artifact.Relic("Tome of Fire", Slot.side, None, [spell.name for spell in Spells('base').Fire()]))
DATA.append(Artifact.Relic("Tome of Water", Slot.side, None, [spell.name for spell in Spells('base').Water()]))
DATA.append(Artifact.Minor("Torso of Legion", Slot.side))
DATA.append(Artifact.Major("Tunic of the Cyclops King", Slot.armor, [0,  0, +4,  0]))
DATA.append(Artifact.Minor("Vampire's Cowl", Slot.cloak))
DATA.append(Artifact.Relic("Vial of Lifeblood", Slot.side))

# The Grail