from ..spell import Spell


DATA = []

DATA.append(Spell.Air("Air Shield", 3))
DATA.append(Spell.Earth("Animate Dead", 3))
DATA.append(Spell.Earth("Anti-Magic", 3))
DATA.append(Spell.Fire("Armageddon", 4))
DATA.append(Spell.Fire("Berserk", 4))
DATA.append(Spell.Water("Bless", 1))
DATA.append(Spell.Fire("Blind", 2))
DATA.append(Spell.Fire("Bloodlust", 1))
DATA.append(Spell.Air("Chain Lightning", 4))
DATA.append(Spell.Water("Clone", 4))
DATA.append(Spell.Air("Counterstrike", 4))
DATA.append(Spell.Water("Cure", 1))
DATA.append(Spell.Fire("Curse", 1))
DATA.append(Spell.Earth("Death Ripple", 2))
DATA.append(Spell.Air("Destroy Undead", 3))
DATA.append(Spell.Air("Dimension Door", 5))
DATA.append(Spell.Air("Disguise", 2))
DATA.append(Spell.Water("Dispel", 1))
DATA.append(Spell.Air("Disrupting Ray", 2))
DATA.append(Spell.Earth("Earthquake", 3))
DATA.append(Spell.Fire("Fire Shield", 4))
DATA.append(Spell.Fire("Fire Wall", 2))
DATA.append(Spell.Fire("Fireball", 3))
DATA.append(Spell.Air("Fly", 5))
DATA.append(Spell.Earth("Force Field", 3))
DATA.append(Spell.Water("Forgetfulness", 2))
DATA.append(Spell.Air("Fortune", 2))
DATA.append(Spell.Fire("Frenzy", 4))
DATA.append(Spell.Water("Frost Ring", 3))
DATA.append(Spell.Air("Haste", 1))
DATA.append(Spell.Air("Hypnotize", 3))
DATA.append(Spell.Water("Ice Bolt", 2))
DATA.append(Spell.Earth("Implosion", 5))
DATA.append(Spell.Fire("Inferno", 4))
DATA.append(Spell.Fire("Land Mine", 3))
DATA.append(Spell.Air("Lightning Bolt", 2))
DATA.append(Spell.Air("Magic Arrow", 1))
DATA.append(Spell.Earth("Magic Arrow", 1))
DATA.append(Spell.Fire("Magic Arrow", 1))
DATA.append(Spell.Water("Magic Arrow", 1))
DATA.append(Spell.Air("Magic Mirror", 5))
DATA.append(Spell.Earth("Meteor Shower", 4))
DATA.append(Spell.Water("Mirth", 3))
DATA.append(Spell.Fire("Misfortune", 3))
DATA.append(Spell.Water("Prayer", 4))
DATA.append(Spell.Air("Precision", 2))
DATA.append(Spell.Air("Protection from Air", 2))
DATA.append(Spell.Earth("Protection from Earth", 3))
DATA.append(Spell.Fire("Protection from Fire", 1))
DATA.append(Spell.Water("Protection from Water", 1))
DATA.append(Spell.Earth("Quick Sand", 2))
DATA.append(Spell.Water("Remove Obstacle", 2))
DATA.append(Spell.Earth("Resurrection", 4))
DATA.append(Spell.Fire("Sacrifice", 5))
DATA.append(Spell.Water("Scuttle Boat", 2))
DATA.append(Spell.Earth("Shield", 1))
DATA.append(Spell.Fire("Slayer", 4))
DATA.append(Spell.Earth("Slow", 1))
DATA.append(Spell.Earth("Sorrow", 4))
DATA.append(Spell.Earth("Stone Skin", 1))
DATA.append(Spell.Air("Summon Air Elemental", 5))
DATA.append(Spell.Water("Summon Boat", 1))
DATA.append(Spell.Earth("Summon Earth Elemental", 5))
DATA.append(Spell.Fire("Summon Fire Elemental", 5))
DATA.append(Spell.Water("Summon Water Elemental", 5))
DATA.append(Spell.Water("Teleport", 3))
DATA.append(Spell.Earth("Town Portal", 4))
DATA.append(Spell.Water("Water Walk", 4))
DATA.append(Spell.Water("Weakness", 2))
DATA.append(Spell.Air("View Air", 1))
DATA.append(Spell.Earth("View Earth", 1))
DATA.append(Spell.Air("Visions", 2))
DATA.append(Spell.Earth("Visions", 2))
DATA.append(Spell.Fire("Visions", 2))
DATA.append(Spell.Water("Visions", 2))
